export const types = {
  GET_NEWS_IDS_SUCCESS: 'GET_NEWS_IDS_SUCCESS',
  GET_NEWS_IDS_FAILURE: 'GET_NEWS_IDS_FAILURE',

  GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
  GET_NEWS_FAILURE: 'GET_NEWS_FAILURE',

  GET_CURRENT_ITEM_SUCCESS: 'GET_CURRENT_ITEM_SUCCESS',
  GET_CURRENT_ITEM_FAILURE: 'GET_CURRENT_ITEM_FAILURE',

  GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
  GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',

  GET_KID_COMMENTS_SUCCESS: 'GET_KID_COMMENTS_SUCCESS',
  GET_KID_COMMENTS_FAILURE: 'GET_KID_COMMENTS_FAILURE',
};
