export const types = {
  GET_NEWS_IDS_SUCCESS: 'GET_NEWS_IDS_SUCCESS',
  GET_NEWS_IDS_FAILURE: 'GET_NEWS_IDS_FAILURE',

  GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
  GET_NEWS_FAILURE: 'GET_NEWS_FAILURE',

  GET_CURRENT_ITEM_SUCCESS: 'GET_CURRENT_ITEM_SUCCESS',
  GET_CURRENT_ITEM_FAILURE: 'GET_CURRENT_ITEM_FAILURE',

  GET_COMMENT_SUCCESS: 'GET_COMMENT_SUCCESS',
  GET_COMMENT_FAILURE: 'GET_COMMENT_FAILURE',
};
