export const types = {
  GET_NEWS_IDS_SUCCESS: 'GET_NEWS_IDS_SUCCESS',
  GET_NEWS_IDS_FAILURE: 'GET_NEWS_IDS_FAILURE',

  GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
  GET_NEWS_FAILURE: 'GET_NEWS_FAILURE',
};
